apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-booking
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flight-booking
  template:
    metadata:
      labels:
        app: flight-booking
    spec:
      dnsPolicy: Default
      containers:
      - name: flight-booking
        image: medaminehz/flight-booking:11
        ports:
        - containerPort: 3006 
