apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-booking-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: car-rental-booking
  template:
    metadata:
      labels:
        app: car-rental-booking
    spec:
      containers:
      - name: car-rental-booking
        image: medaminehz/car-rental-booking:tagname
        ports:
        - containerPort: 50051 
