apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-booking
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hotels-booking
  template:
    metadata:
      labels:
        app: hotels-booking
    spec:
      dnsPolicy: Default
      containers:
      - name: hotels-booking
        image: medaminehz/hotels-booking:10
        ports:
        - containerPort: 3006 
